import './globals.css'
import type { Metadata } from 'next'
import { Inter, Shippori_Antique } from 'next/font/google'


export const metadata: Metadata = {
  title: 'Image Gallery',
  description: 'Generated by create next app',
}
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})
const shippori = Shippori_Antique({
  subsets: ['latin'],
  variable: '--font-shi',
  display: 'swap',
  weight: ['400']
})
 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={` ${inter.variable}  ${shippori.variable}`}>
      <body >{children}</body>
    </html>
  )
}
